"""
conversation-service/app/swarm/state.py
The shared state schema flowing through the LangGraph agent swarm.

V3 Changes:
  - intent_confidence: float — how certain the intent classifier is
  - lead_score: float — visitor purchase readiness (0.0–1.0)
  - conversation_plan: list[str] — multi-step plan generated by PlannerAgent
  - plan_step: int — current step in the plan
  - session_memory: dict — short-term memory (preferences, entities mentioned)
  - long_term_context: str — summary injected from prior sessions
"""
from typing import TypedDict, Annotated, Sequence
from langchain_core.messages import BaseMessage
import operator


class AgentState(TypedDict):
    # Core message stream
    messages: Annotated[Sequence[BaseMessage], operator.add]

    # Intent classification
    intent: str
    intent_confidence: float

    # Sales intelligence
    lead_score: float

    # Planning
    conversation_plan: list[str]
    plan_step: int

    # Memory
    session_memory: dict
    long_term_context: str

    # Business context passed in at start
    context: dict
    
    # Knowledge retrieval results
    knowledge_context: str
    knowledge_confidence: float

    # Avatar Emotion
    emotion_data: dict
